### PR TITLE
enable iPXE boot

### PR DESCRIPTION
**Pull request by jovial**
This depends on stackhpc/kayobe#140

### CODE REVIEW

**Review by markgoddard — APPROVED** [review]

**Comment by markgoddard** [comment]
Have the dependent changes in kolla, kolla-ansible and kayobe been backported to the stackhpc/pike branches?

**Comment by jovial** [comment]
Still waiting on stackhpc/kayobe#144

these ones are in:
stackhpc/kolla-ansible#29
stackhpc/kolla#6

**Comment by markgoddard** [comment]
Created a PR for kayobe stackhpc/pike: https://github.com/SKA-ScienceDataProcessor/alaska-kayobe-config/pull/66

**Comment by jovial** [comment]
stackhpc/kayobe#145 is now merged. This should be good to go.

**Pull request merged**
