### PR TITLE
Alaska prod alarm template

### PR DESCRIPTION
**Pull request by Wasaac**
QoL improvements to the Monasca alarm Slack template. Neater list of affected hosts + url points to the Grafana plugin with host field filled.
Mirrors: https://github.com/SKA-ScienceDataProcessor/alaska-kayobe-config/pull/196

### CODE REVIEW

**Review by brtkwr — APPROVED** [review]

**Review by dougszumski — COMMENTED** [review]
Any example renderings of the template from alt-1?

**Comment by Wasaac** [comment]
> Any example renderings of the template from alt-1?

Alarm template currently in use on Alt-1. AD Slack, channel alt-1-alerts. 
Looks like:
```
Memory Usage - State: OK. Hosts: myhost-23 http://192.168.128.100:3000/plugins/monasca-app/page/alarms?dimensions=hostname:myhost-23
```

**Comment by dougszumski** [comment]
Does the app page handle the case when multiples hosts are specified?

**Comment by Wasaac** [comment]
> Does the app page handle the case when multiples hosts are specified?

Theoretically yes but we're lacking alarm definitions on alt-1 to test with. There are alarms with multiple hostnames in metric dimensions but they're all the same hostname - an example from my vagrant dev env using the default slack template:
```
Network Errors - State: OK. Hosts: operator, operator, operator, operator, operator, operator, operator, operator, operator, operator
```
Now becomes:
```
Network Errors - State: OK. Hosts: operator
```
And the url generated for a single host works successfully. 
Testing manually the url works for multiple hostnames. eg:
```
{{ url }}/plugins/monasca-app/page/alarms?dimensions=hostname:operator|operator-test
```
So there's no reason to believe it wouldn't.

**Review by dougszumski — APPROVED** [review]
Ok, thanks

**Pull request merged**
